services:
    tgcollector-db:
        container_name: tgcollector-db
        image: mariadb
        cap_add:
            - SYS_NICE
        networks:
            - network
        restart: always
        environment:
            MYSQL_DATABASE: tgplan_ru
            MYSQL_ROOT_PASSWORD: uKatshzCBg1331
            MYSQL_USER: tgplan_ru
            MYSQL_PASSWORD: uKatshzCBg1331
        ports:
            - '3308:3306'
        volumes:
            - ./docker/db/db_data:/var/lib/mysql
            - ./docker/db/dumps:/docker-entrypoint-initdb.d
    clickhouse:
        container_name: clickhouse
        image: clickhouse/clickhouse-server:latest
        volumes:
            - ./docker/clickhouse/db_data:/var/lib/clickhouse
            - ./docker/clickhouse/config.xml:/etc/clickhouse-server/config.xml
        ports:
        - "8002:9000"
        - "9123:8123"
        restart: always
        ulimits:
            nproc: 65535
            nofile:
                soft: 262144
                hard: 262144
        networks:
            - network
    rabbitmq:
        container_name: rabbitmq
        image: rabbitmq:3-management-alpine
        ports:
            - 5672:5672
            - 15672:15672
        restart: always
        volumes:
            - ./docker/rabbitmq/data/:/var/lib/rabbitmq/
            - ./docker/rabbitmq/log/:/var/log/rabbitmq
        networks:
            - network
    tgcollector-app:
        container_name: tgcollector-app
        build:
            context: ./
            network: host
        restart: always
        networks:
            - network
        ports:
            - "9002:9000"
        volumes:
            - ./docker/php/php.ini:/usr/local/etc/php/php.ini
        working_dir: /var/www
    bot:
        container_name: bot
        build: ./docker/bot
        command: ["python", "task_bot.py"]
        networks:
            - network
        restart: always
        stdin_open: true
        tty: true
        volumes:
            - ./docker/bot:/var/www/
        working_dir: /var/www/
    tgcollector-nginx:
        container_name: tgcollector-nginx
        image: nginx:alpine
        ports:
            - "82:80"
            - "445:443"
        restart: always
        networks:
            - network
        volumes_from:
            - tgcollector-app
        volumes:
            - ./:/var/www
            - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - tgcollector-db
            - tgcollector-app
    horizon:
        container_name: horizon
        build: ./
        command: php artisan horizon
        restart: always
        networks:
            - network
        working_dir: /var/www

networks:
  network:
    driver: bridge
